# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'J_slaveUi.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_J_slaveWin(object):
    def setupUi(self, J_slaveWin):
        J_slaveWin.setObjectName(_fromUtf8("J_slaveWin"))
        J_slaveWin.resize(1035, 780)
        self.centralwidget = QtGui.QWidget(J_slaveWin)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.comboBox_slaveList = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_slaveList.sizePolicy().hasHeightForWidth())
        self.comboBox_slaveList.setSizePolicy(sizePolicy)
        self.comboBox_slaveList.setMaximumSize(QtCore.QSize(220, 50))
        self.comboBox_slaveList.setObjectName(_fromUtf8("comboBox_slaveList"))
        self.gridLayout.addWidget(self.comboBox_slaveList, 0, 0, 1, 1)
        self.pushButton_findSlave = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_findSlave.sizePolicy().hasHeightForWidth())
        self.pushButton_findSlave.setSizePolicy(sizePolicy)
        self.pushButton_findSlave.setMaximumSize(QtCore.QSize(100, 50))
        self.pushButton_findSlave.setObjectName(_fromUtf8("pushButton_findSlave"))
        self.gridLayout.addWidget(self.pushButton_findSlave, 0, 1, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMaximumSize(QtCore.QSize(220, 50))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.pushButton_connectSlave = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_connectSlave.sizePolicy().hasHeightForWidth())
        self.pushButton_connectSlave.setSizePolicy(sizePolicy)
        self.pushButton_connectSlave.setMaximumSize(QtCore.QSize(100, 50))
        self.pushButton_connectSlave.setObjectName(_fromUtf8("pushButton_connectSlave"))
        self.gridLayout.addWidget(self.pushButton_connectSlave, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.listView_job = QtGui.QListView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_job.sizePolicy().hasHeightForWidth())
        self.listView_job.setSizePolicy(sizePolicy)
        self.listView_job.setMinimumSize(QtCore.QSize(330, 0))
        self.listView_job.setMaximumSize(QtCore.QSize(330, 16777215))
        self.listView_job.setObjectName(_fromUtf8("listView_job"))
        self.verticalLayout.addWidget(self.listView_job)
        self.listView_job_2 = QtGui.QListView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_job_2.sizePolicy().hasHeightForWidth())
        self.listView_job_2.setSizePolicy(sizePolicy)
        self.listView_job_2.setMinimumSize(QtCore.QSize(330, 0))
        self.listView_job_2.setMaximumSize(QtCore.QSize(330, 16777215))
        self.listView_job_2.setObjectName(_fromUtf8("listView_job_2"))
        self.verticalLayout.addWidget(self.listView_job_2)
        self.listView_log = QtGui.QListView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_log.sizePolicy().hasHeightForWidth())
        self.listView_log.setSizePolicy(sizePolicy)
        self.listView_log.setMinimumSize(QtCore.QSize(330, 0))
        self.listView_log.setMaximumSize(QtCore.QSize(330, 16777215))
        self.listView_log.setObjectName(_fromUtf8("listView_log"))
        self.verticalLayout.addWidget(self.listView_log)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.tableView_worker = QtGui.QTableView(self.centralwidget)
        self.tableView_worker.setMinimumSize(QtCore.QSize(650, 650))
        self.tableView_worker.setMaximumSize(QtCore.QSize(800, 800))
        self.tableView_worker.setObjectName(_fromUtf8("tableView_worker"))
        self.verticalLayout_2.addWidget(self.tableView_worker)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_addJob = QtGui.QPushButton(self.centralwidget)
        self.pushButton_addJob.setObjectName(_fromUtf8("pushButton_addJob"))
        self.horizontalLayout.addWidget(self.pushButton_addJob)
        self.pushButton_removeJob = QtGui.QPushButton(self.centralwidget)
        self.pushButton_removeJob.setObjectName(_fromUtf8("pushButton_removeJob"))
        self.horizontalLayout.addWidget(self.pushButton_removeJob)
        self.pushButton_startJob = QtGui.QPushButton(self.centralwidget)
        self.pushButton_startJob.setObjectName(_fromUtf8("pushButton_startJob"))
        self.horizontalLayout.addWidget(self.pushButton_startJob)
        self.pushButton_stopJob = QtGui.QPushButton(self.centralwidget)
        self.pushButton_stopJob.setObjectName(_fromUtf8("pushButton_stopJob"))
        self.horizontalLayout.addWidget(self.pushButton_stopJob)
        self.pushButton_startWorker = QtGui.QPushButton(self.centralwidget)
        self.pushButton_startWorker.setObjectName(_fromUtf8("pushButton_startWorker"))
        self.horizontalLayout.addWidget(self.pushButton_startWorker)
        self.pushButton_stopWorker = QtGui.QPushButton(self.centralwidget)
        self.pushButton_stopWorker.setObjectName(_fromUtf8("pushButton_stopWorker"))
        self.horizontalLayout.addWidget(self.pushButton_stopWorker)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        J_slaveWin.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(J_slaveWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1035, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        J_slaveWin.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(J_slaveWin)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        J_slaveWin.setStatusBar(self.statusbar)

        self.retranslateUi(J_slaveWin)
        QtCore.QMetaObject.connectSlotsByName(J_slaveWin)

    def retranslateUi(self, J_slaveWin):
        J_slaveWin.setWindowTitle(_translate("J_slaveWin", "MainWindow", None))
        self.pushButton_findSlave.setText(_translate("J_slaveWin", "FindSlaves", None))
        self.pushButton_connectSlave.setText(_translate("J_slaveWin", "ConnectSlave", None))
        self.label.setText(_translate("J_slaveWin", "Jobs", None))
        self.label_2.setText(_translate("J_slaveWin", "Logs", None))
        self.pushButton_addJob.setText(_translate("J_slaveWin", "AddJobs", None))
        self.pushButton_removeJob.setText(_translate("J_slaveWin", "RemoveJobs", None))
        self.pushButton_startJob.setText(_translate("J_slaveWin", "StartJobs", None))
        self.pushButton_stopJob.setText(_translate("J_slaveWin", "stopJobs", None))
        self.pushButton_startWorker.setText(_translate("J_slaveWin", "StartWorker", None))
        self.pushButton_stopWorker.setText(_translate("J_slaveWin", "StopWorker", None))

