# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'J_workerUi.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_J_managerWin(object):
    def setupUi(self, J_managerWin):
        J_managerWin.setObjectName(_fromUtf8("J_managerWin"))
        J_managerWin.setEnabled(True)
        J_managerWin.resize(1024, 720)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(J_managerWin.sizePolicy().hasHeightForWidth())
        J_managerWin.setSizePolicy(sizePolicy)
        J_managerWin.setMinimumSize(QtCore.QSize(1024, 720))
        J_managerWin.setMaximumSize(QtCore.QSize(1024, 720))
        self.centralwidget = QtGui.QWidget(J_managerWin)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tableView_worker = QtGui.QTableView(self.centralwidget)
        self.tableView_worker.setGeometry(QtCore.QRect(350, 40, 650, 580))
        self.tableView_worker.setMinimumSize(QtCore.QSize(650, 550))
        self.tableView_worker.setMaximumSize(QtCore.QSize(800, 600))
        self.tableView_worker.setObjectName(_fromUtf8("tableView_worker"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 10, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pushButton_stopWorker = QtGui.QPushButton(self.centralwidget)
        self.pushButton_stopWorker.setGeometry(QtCore.QRect(660, 640, 120, 25))
        self.pushButton_stopWorker.setObjectName(_fromUtf8("pushButton_stopWorker"))
        self.pushButton_startWorker = QtGui.QPushButton(self.centralwidget)
        self.pushButton_startWorker.setGeometry(QtCore.QRect(530, 640, 120, 25))
        self.pushButton_startWorker.setObjectName(_fromUtf8("pushButton_startWorker"))
        self.pushButton_startJob = QtGui.QPushButton(self.centralwidget)
        self.pushButton_startJob.setGeometry(QtCore.QRect(270, 640, 120, 25))
        self.pushButton_startJob.setObjectName(_fromUtf8("pushButton_startJob"))
        self.pushButton_removeJob = QtGui.QPushButton(self.centralwidget)
        self.pushButton_removeJob.setGeometry(QtCore.QRect(140, 640, 120, 25))
        self.pushButton_removeJob.setObjectName(_fromUtf8("pushButton_removeJob"))
        self.pushButton_stopJob = QtGui.QPushButton(self.centralwidget)
        self.pushButton_stopJob.setGeometry(QtCore.QRect(400, 640, 120, 25))
        self.pushButton_stopJob.setObjectName(_fromUtf8("pushButton_stopJob"))
        self.pushButton_addJob = QtGui.QPushButton(self.centralwidget)
        self.pushButton_addJob.setGeometry(QtCore.QRect(10, 640, 120, 25))
        self.pushButton_addJob.setObjectName(_fromUtf8("pushButton_addJob"))
        self.listView_log = QtGui.QListView(self.centralwidget)
        self.listView_log.setGeometry(QtCore.QRect(10, 430, 330, 192))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_log.sizePolicy().hasHeightForWidth())
        self.listView_log.setSizePolicy(sizePolicy)
        self.listView_log.setMinimumSize(QtCore.QSize(330, 0))
        self.listView_log.setMaximumSize(QtCore.QSize(330, 16777215))
        self.listView_log.setObjectName(_fromUtf8("listView_log"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 400, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.listView_job_2 = QtGui.QListView(self.centralwidget)
        self.listView_job_2.setGeometry(QtCore.QRect(10, 250, 330, 140))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_job_2.sizePolicy().hasHeightForWidth())
        self.listView_job_2.setSizePolicy(sizePolicy)
        self.listView_job_2.setMinimumSize(QtCore.QSize(330, 0))
        self.listView_job_2.setMaximumSize(QtCore.QSize(330, 16777215))
        self.listView_job_2.setObjectName(_fromUtf8("listView_job_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 220, 44, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.listView_job = QtGui.QListView(self.centralwidget)
        self.listView_job.setGeometry(QtCore.QRect(11, 73, 330, 140))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_job.sizePolicy().hasHeightForWidth())
        self.listView_job.setSizePolicy(sizePolicy)
        self.listView_job.setMinimumSize(QtCore.QSize(330, 0))
        self.listView_job.setMaximumSize(QtCore.QSize(330, 16777215))
        self.listView_job.setObjectName(_fromUtf8("listView_job"))
        self.pushButton_connectWorker = QtGui.QPushButton(self.centralwidget)
        self.pushButton_connectWorker.setGeometry(QtCore.QRect(229, 10, 111, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_connectWorker.sizePolicy().hasHeightForWidth())
        self.pushButton_connectWorker.setSizePolicy(sizePolicy)
        self.pushButton_connectWorker.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_connectWorker.setObjectName(_fromUtf8("pushButton_connectWorker"))
        self.lineEdit_ipPort = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_ipPort.setGeometry(QtCore.QRect(12, 10, 200, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ipPort.sizePolicy().hasHeightForWidth())
        self.lineEdit_ipPort.setSizePolicy(sizePolicy)
        self.lineEdit_ipPort.setMaximumSize(QtCore.QSize(220, 50))
        self.lineEdit_ipPort.setObjectName(_fromUtf8("lineEdit_ipPort"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(12, 40, 171, 20))
        self.label.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        J_managerWin.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(J_managerWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        J_managerWin.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(J_managerWin)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        J_managerWin.setStatusBar(self.statusbar)

        self.retranslateUi(J_managerWin)
        QtCore.QMetaObject.connectSlotsByName(J_managerWin)

    def retranslateUi(self, J_managerWin):
        J_managerWin.setWindowTitle(_translate("J_managerWin", "MainWindow", None))
        self.label_2.setText(_translate("J_managerWin", "Logs", None))
        self.pushButton_stopWorker.setText(_translate("J_managerWin", "StopWorker", None))
        self.pushButton_startWorker.setText(_translate("J_managerWin", "StartWorker", None))
        self.pushButton_startJob.setText(_translate("J_managerWin", "StartJobs", None))
        self.pushButton_removeJob.setText(_translate("J_managerWin", "RemoveJobs", None))
        self.pushButton_stopJob.setText(_translate("J_managerWin", "stopJobs", None))
        self.pushButton_addJob.setText(_translate("J_managerWin", "AddJobs", None))
        self.label_4.setText(_translate("J_managerWin", "Job Info", None))
        self.label_3.setText(_translate("J_managerWin", "Jobs", None))
        self.pushButton_connectWorker.setText(_translate("J_managerWin", "ConnectWorker", None))
        self.label.setText(_translate("J_managerWin", "WorkerInfo", None))

