# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'J_VideoConverterCutUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_setTime_win(object):
    def setupUi(self, setTime_win):
        setTime_win.setObjectName(_fromUtf8("setTime_win"))
        setTime_win.resize(534, 179)
        self.label_movName = QtGui.QLabel(setTime_win)
        self.label_movName.setGeometry(QtCore.QRect(20, 10, 331, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_movName.setFont(font)
        self.label_movName.setObjectName(_fromUtf8("label_movName"))
        self.lineEdit_st1 = QtGui.QLineEdit(setTime_win)
        self.lineEdit_st1.setGeometry(QtCore.QRect(20, 80, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_st1.setFont(font)
        self.lineEdit_st1.setMaxLength(600)
        self.lineEdit_st1.setObjectName(_fromUtf8("lineEdit_st1"))
        self.lineEdit_st2 = QtGui.QLineEdit(setTime_win)
        self.lineEdit_st2.setGeometry(QtCore.QRect(60, 80, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_st2.setFont(font)
        self.lineEdit_st2.setMaxLength(600)
        self.lineEdit_st2.setObjectName(_fromUtf8("lineEdit_st2"))
        self.lineEdit_st3 = QtGui.QLineEdit(setTime_win)
        self.lineEdit_st3.setGeometry(QtCore.QRect(100, 80, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_st3.setFont(font)
        self.lineEdit_st3.setMaxLength(600)
        self.lineEdit_st3.setObjectName(_fromUtf8("lineEdit_st3"))
        self.lineEdit_et3 = QtGui.QLineEdit(setTime_win)
        self.lineEdit_et3.setGeometry(QtCore.QRect(260, 80, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_et3.setFont(font)
        self.lineEdit_et3.setMaxLength(600)
        self.lineEdit_et3.setObjectName(_fromUtf8("lineEdit_et3"))
        self.lineEdit_et2 = QtGui.QLineEdit(setTime_win)
        self.lineEdit_et2.setGeometry(QtCore.QRect(220, 80, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_et2.setFont(font)
        self.lineEdit_et2.setMaxLength(600)
        self.lineEdit_et2.setObjectName(_fromUtf8("lineEdit_et2"))
        self.lineEdit_et1 = QtGui.QLineEdit(setTime_win)
        self.lineEdit_et1.setGeometry(QtCore.QRect(180, 80, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_et1.setFont(font)
        self.lineEdit_et1.setMaxLength(600)
        self.lineEdit_et1.setObjectName(_fromUtf8("lineEdit_et1"))
        self.pushButton_cutVideo = QtGui.QPushButton(setTime_win)
        self.pushButton_cutVideo.setGeometry(QtCore.QRect(20, 130, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_cutVideo.setFont(font)
        self.pushButton_cutVideo.setObjectName(_fromUtf8("pushButton_cutVideo"))
        self.pushButton_nextVideo = QtGui.QPushButton(setTime_win)
        self.pushButton_nextVideo.setGeometry(QtCore.QRect(180, 130, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_nextVideo.setFont(font)
        self.pushButton_nextVideo.setObjectName(_fromUtf8("pushButton_nextVideo"))
        self.label_movName_2 = QtGui.QLabel(setTime_win)
        self.label_movName_2.setGeometry(QtCore.QRect(20, 40, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_movName_2.setFont(font)
        self.label_movName_2.setObjectName(_fromUtf8("label_movName_2"))
        self.label_movName_3 = QtGui.QLabel(setTime_win)
        self.label_movName_3.setGeometry(QtCore.QRect(180, 42, 61, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_movName_3.setFont(font)
        self.label_movName_3.setObjectName(_fromUtf8("label_movName_3"))
        self.lineEdit_crf = QtGui.QLineEdit(setTime_win)
        self.lineEdit_crf.setGeometry(QtCore.QRect(330, 80, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_crf.setFont(font)
        self.lineEdit_crf.setMaxLength(600)
        self.lineEdit_crf.setObjectName(_fromUtf8("lineEdit_crf"))
        self.label_movName_4 = QtGui.QLabel(setTime_win)
        self.label_movName_4.setGeometry(QtCore.QRect(330, 40, 31, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_movName_4.setFont(font)
        self.label_movName_4.setObjectName(_fromUtf8("label_movName_4"))
        self.label_movName_5 = QtGui.QLabel(setTime_win)
        self.label_movName_5.setGeometry(QtCore.QRect(400, 40, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_movName_5.setFont(font)
        self.label_movName_5.setObjectName(_fromUtf8("label_movName_5"))
        self.comboBox_resolution = QtGui.QComboBox(setTime_win)
        self.comboBox_resolution.setGeometry(QtCore.QRect(400, 80, 81, 22))
        self.comboBox_resolution.setObjectName(_fromUtf8("comboBox_resolution"))
        self.comboBox_resolution.addItem(_fromUtf8(""))
        self.comboBox_resolution.addItem(_fromUtf8(""))
        self.comboBox_resolution.addItem(_fromUtf8(""))
        self.comboBox_resolution.addItem(_fromUtf8(""))
        self.comboBox_resolution.addItem(_fromUtf8(""))
        self.label_movNameP = QtGui.QLabel(setTime_win)
        self.label_movNameP.setGeometry(QtCore.QRect(400, 10, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_movNameP.setFont(font)
        self.label_movNameP.setObjectName(_fromUtf8("label_movNameP"))
        self.pushButton_delete = QtGui.QPushButton(setTime_win)
        self.pushButton_delete.setGeometry(QtCore.QRect(350, 130, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setObjectName(_fromUtf8("pushButton_delete"))

        self.retranslateUi(setTime_win)
        QtCore.QMetaObject.connectSlotsByName(setTime_win)

    def retranslateUi(self, setTime_win):
        setTime_win.setWindowTitle(_translate("setTime_win", "setTime", None))
        self.label_movName.setText(_translate("setTime_win", "filename", None))
        self.pushButton_cutVideo.setText(_translate("setTime_win", "Cut", None))
        self.pushButton_nextVideo.setText(_translate("setTime_win", "Next", None))
        self.label_movName_2.setText(_translate("setTime_win", "startTime", None))
        self.label_movName_3.setText(_translate("setTime_win", "endTime", None))
        self.label_movName_4.setText(_translate("setTime_win", "crf", None))
        self.label_movName_5.setText(_translate("setTime_win", "resolution", None))
        self.comboBox_resolution.setItemText(0, _translate("setTime_win", "ori", None))
        self.comboBox_resolution.setItemText(1, _translate("setTime_win", "720*405", None))
        self.comboBox_resolution.setItemText(2, _translate("setTime_win", "1024*540", None))
        self.comboBox_resolution.setItemText(3, _translate("setTime_win", "1280*720", None))
        self.comboBox_resolution.setItemText(4, _translate("setTime_win", "1920*1080", None))
        self.label_movNameP.setText(_translate("setTime_win", "filename", None))
        self.pushButton_delete.setText(_translate("setTime_win", "Delete", None))

