//  @package public
//
//  @brief   安装工具
//  @author 桔
//  @version 1.0
//  @date   18:18 2020/9/27
//  History:  
//
global proc J_autoInstallMadOnion()
{
    string $pathStr= `whatIs J_autoInstallMadOnion`;
    string $runPy="";
    $runPy+="import maya.mel as mel \nimport maya.cmds as cmds\nimport os,stat\n";
    $runPy+="pathStr='"+$pathStr+"'\n";
    $runPy+="userSetup=pathStr.replace('Mel procedure found in: ','').replace('J_autoInstallMadOnion.mel','userSetup.mel')\n";
    
    $runPy+="userSetupFile=open(userSetup,'r')\n";
    $runPy+="userSetupStr=userSetupFile.read()\nuserSetupFile.close()\n";
    $runPy+="userSetupStr=userSetupStr.replace('your path',userSetup.replace('userSetup.mel',''))\n";
    $runPy+="userSetupFilePath=os.path.dirname(os.path.dirname(os.path.dirname(cmds.internalVar(userScriptDir=True).replace('zh_CN/',''))))+'/scripts/userSetup.mel'\n";
    
    $runPy+="if os.path.exists(userSetupFilePath):\n";
    $runPy+="    os.remove(userSetupFilePath)\n";
    
    $runPy+="userSetupFile=open(userSetupFilePath,'w')\n";
    $runPy+="userSetupFile.write(userSetupStr )\nuserSetupFile.close()\nmel.eval(userSetupStr)\n";
    $runPy+="os.chmod(userSetupFilePath,stat.S_IREAD) \n";
    python($runPy);
}

J_autoInstallMadOnion();