/////////////////////////////////////////////////////////////
///\file  J_killaiMode.mel
///\brief  \
///
///\author ½Û
///\version 1.0
///\date   15:14 2018/1/16
///History:  
///
///////////////////////////////////////////////////////////////

///
global proc J_killaiMode()
{string $sel[]=`ls -sl`;
    for ($i in $sel)
        {
            if (`attributeExists "aiMode" $i `)
                {deleteAttr -at "aiMode" $i;}
        }
}