/////////////////////////////////////////////////////////////
///\file  J_unLockAttrs.mel
///\brief  所有属性解锁
///
///\author 桔
///\version 1.0
///\date   16:41 2018/1/16
///History:  
///
///////////////////////////////////////////////////////////////

///所有属性解锁
global proc J_unLockAttrs()
{
string $mos[]=`ls -sl`;
for($item in $mos)
	{
		string $lockedAttrs[]=`listAttr -l $item`;
		for($itemA in $lockedAttrs)
		{
		setAttr -lock 0 ($item+"."+$itemA);
		}

	}
}
